---
# This playbook deploy a secure mongodb replica set on Ubuntu hosts

# Install mongodb on each nodes
- hosts: all
  remote_user: ubuntu
  sudo: True
  roles:
  - role: install-mongod-wt-rs



# - hosts: primary
#   remote_user: ubuntu
#   sudo: True
#   roles:
#   - role: mount-mongodb

# Restart Primary taking into account the new configuration (/etc/mongod.conf)
- hosts: primary
  remote_user: ubuntu
  sudo: true
  roles:
  - role: restart_mongod
  - role: wait_connection

# Initiate the replicaset and create the admin users
- hosts: primary
  remote_user: ubuntu
  sudo: True
  roles:
  - role: initiate-replica-set
  - role: wait_master
  - role: create_admin_users

# Create key file
- hosts: localhost
  tasks:
  - name: create key file locally
    local_action: shell openssl rand -base64 755 > /tmp/mongodb-keyfile

# Copy key file to each node
- hosts: all
  remote_user: ubuntu
  sudo: True
  roles:
  - role: set_key_files

# Restart Primary taking into account the new configuration (auth / keyFile option defined in /etc/mongod.conf)
- hosts: primary
  remote_user: ubuntu
  sudo: true
  roles:
  - role: restart_mongod
  - role: wait_master

# Restart Secondaries taking into account the new configuration (auth / keyFile option defined in /etc/mongod.conf)
- hosts: secondary
  remote_user: ubuntu
  sudo: true
  roles:
  - role: restart_mongod
  - role: wait_connection

# Add members to the replicaset and create user for the database
- hosts: primary
  remote_user: ubuntu
  sudo: True
  roles:
  - role: add-members
  - role: create_users
