---
- include: check_vars.yml

- include: download.yml
  tags:
    - download

- include: dependencies.yml
  tags:
    - install

- include: install.yml
  tags:
    - install

- include: server.yml
  tags:
    - config

- include: sentinel.yml
  tags:
    - config

- include: local_facts.yml
  when: redis_local_facts|bool
