---
- name: "restart redis {{ redis_service_name }}"
  service:
    name: "{{ redis_service_name }}"
    state: restarted
  when: redis_as_service

- name: "restart sentinel {{ redis_sentinel_port }}"
  service:
    name: sentinel
    state: restarted
  when: redis_as_service
